[package]
name = "dst-init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true
opt-level = 3
strip = true

[dependencies]
dst-init-macros={path="./dst-init-macros",version="0.1.0"}
